version: "3.9"
services:
  map4sci:
    image: map4sci:latest
    # build: .
    volumes:
      - type: bind
        source: ./data-processor/datasets
        target: /workspace/data-processor/datasets
      - type: bind
        source: ./data-processor/raw-data
        target: /workspace/data-processor/raw-data
    stdin_open: true # docker run -i
    tty: true        # docker run -t
