version: '3.9'
services:
  map4sci:
    image: map4sci:latest
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 24G
        reservations:
          cpus: '0.25'
          memory: 3G
    volumes:
      - type: bind
        source: ./data-processor/datasets
        target: /workspace/data-processor/datasets
      - type: bind
        source: ./data-processor/raw-data
        target: /workspace/data-processor/raw-data
      - type: bind
        source: ./data-processor/site
        target: /workspace/data-processor/site
    stdin_open: true # docker run -i
    tty: true # docker run -t
    working_dir: /workspace/data-processor/
    environment:
      - CURRENT_DATASET
      - CURRENT_VERSION
      - NODE_OPTIONS
    command: /bin/bash -c 'cd /workspace/data-processor/ && ./run.sh'
