header:
  logo:
    layout: icon-first # Options: icon-first, label-first
    icon: null # Url
    label: TRIPODS # Text
    link-to: null # Url

footer:
  copyright: "Copyright \u00A9 2021 Tripods. All rights reserved." # Text
  terms-of-service: assets/footer/terms.md # Url
  privacy-policy: assets/footer/privacy-policy.md # Url
