name: 'Production Build'

on:
  workflow_run:
    workflows: ['Tests']
    branches: ['main']
    types:
      - completed

jobs:
  deploy:
    name: 'Deploy'
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: npm ci for website
        run: npm ci
        working-directory: website
      - run: npm run build -- --output-hashing=none --base-href=/map4sci/
        working-directory: website
      - name: Build docs
        working-directory: website
        run: |
          npm run build:docs
          cp -r docs/map4sci dist/map4sci
      - name: Setup GitHub Pages files
        working-directory: website
        run: |
          cp dist/map4sci/index.html dist/map4sci/404.html
          touch dist/map4sci/.nojekyll

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/dist/map4sci
          commit_message: "Production deploy -- ${{ github.event.head_commit.message }}"
